// Dashboard.
export const DASHBOARD_DATA_START = 'api/DASHBOARD_DATA_START';
export const DASHBOARD_DATA_SUCCESS = 'api/DASHBOARD_DATA_SUCCESS';
export const DASHBOARD_DATA_FAIL = 'api/DASHBOARD_DATA_FAIL';
